# Generated by Django 4.2.4 on 2023-09-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_todo_date_created_todo_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateTimeField(null=True),
        ),
    ]
